# Generated by Django 3.2.9 on 2021-12-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211204_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='logo',
        ),
    ]
