# Generated by Django 3.2.9 on 2021-12-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_facility_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='value',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='name',
        ),
        migrations.AddField(
            model_name='facility',
            name='bedroom',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='floor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
